name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, task: publishAllPublicationsToSonatypeRepository}
          - {os: macos-latest, task: publishMacosX64PublicationToSonatypeRepository}
          - {os: windows-latest, task: publishMingwX64PublicationToSonatypeRepository}
    name: Publish for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s ${{ matrix.config.task }} closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
